### ISSUE TITLE
Output cjs builds, react-scripts support

### ISSUE THREAD

**Issue by eriksachse** [isaac-mason/recast-navigation-js#140] opened 2023-09-22 11:54 UTC
Repro: https://codesandbox.io/s/sad-dawn-hdq9zf?file=/src/App.js

When using init() within a React app, a syntax Error appears. `Cannot use 'import.meta' outside a module`

**Comment by isaac-mason** [comment] 2023-09-23 00:36
Hi, thanks for the issue & reproduction!

Right now `recast-navigation-js` only has an ESM build, so importing it in a non-esm project has to be done like this: https://github.com/isaac-mason/recast-navigation-js/blob/de28866dec263433db34799592a5a33808ea511c/examples/node-cjs-recast-navigation-example/src/index.js

I acknowledge this isn't ideal though. I want to support the wider r3f community, many of which use CJS still via tools like react-scripts and parcel, so I'm working on outputting regular cjs builds now.

**Comment by isaac-mason** [comment] 2023-09-23 03:32
This should get fixed by https://github.com/isaac-mason/recast-navigation-js/commit/82a1bb170b5d7b4f70e0aac0d080de844412ac3c and https://github.com/isaac-mason/recast-navigation-js/commit/a327743be1cbe53e1a40a0970f01c84a8d63bfea

These will be released shortly

**Comment by isaac-mason** [comment] 2023-09-23 04:26
In v0.9.3 support for react-scripts and parcel (and others) should be fixed.

Interestingly, there are still issues importing `recast-navigation` in the browser codesandbox. 

Downloading the sandbox and running it locally, or using a cloud sandbox, there's no issues though: https://codesandbox.io/p/sandbox/recast-navigation-react-scripts-example-8wy6hh

**Comment by isaac-mason** [comment] 2023-09-23 04:39
Given this looks like a CodeSandbox-specific issue, I'll close this, and we can track the fix for CodeSandbox here: https://github.com/isaac-mason/recast-navigation-js/issues/145

**Closed by isaac-mason** 2023-09-23 04:39 UTC
